/**
 * archon-search pi extension — source of truth
 *
 * This module generates the `.mjs` extension that pi loads at runtime.
 * It is the canonical, version-controlled form of the extension logic.
 * Re-run `archon install-extension` to write it to ~/.pi/extensions/.
 *
 * Architecture overview:
 *   systemPrompt()    — injected into every pi session
 *   contextFooter()   — auto-injects SearXNG results when TRIGGER matches
 *   tools[web_search] — explicit tool pi can call on demand
 */

import { config } from './config.js';

/**
 * Render the extension as an ES-module string ready to write to disk.
 * All runtime config values are baked in as defaults so the extension
 * works even when env vars are not set at pi-launch time.
 */
export function renderExtension(): string {
  const { url, topN, categories, triggerRegex } = config.searxng;
  const { extensionName } = config.pi;

  return `\
// ${extensionName} pi extension
// Auto-generated by archon — do not edit manually.
// Source of truth: src/extension.ts
// Regenerate: archon install-extension

const SEARXNG   = process.env.ARCHON_SEARXNG_URL        ?? '${url}';
const TOP_N     = parseInt(process.env.ARCHON_SEARCH_TOP_N   ?? '${topN}', 10);
const TRIGGER   = new RegExp(process.env.ARCHON_SEARCH_TRIGGER ?? '${triggerRegex.source}', 'i');
const CATEGORIES = process.env.ARCHON_SEARCH_CATEGORIES ?? '${categories}';

/** @param {string} query */
async function searxng(query) {
  try {
    const u = new URL('/search', SEARXNG);
    u.searchParams.set('q', query);
    u.searchParams.set('format', 'json');
    u.searchParams.set('categories', CATEGORIES);
    const res = await fetch(u.toString(), {
      headers: { Accept: 'application/json' },
      signal: AbortSignal.timeout(8_000),
    });
    if (!res.ok) return null;
    const data = await res.json();
    const hits = (data.results ?? []).slice(0, TOP_N);
    if (!hits.length) return null;
    return hits
      .map((r, i) => \`**[\${i + 1}] \${r.title ?? ''}**\n\${r.url ?? ''}\n\${(r.content ?? r.snippet ?? '').trim()}\`)
      .join('\\n\\n');
  } catch {
    return null;
  }
}

export default {
  name: '${extensionName}',

  /** Injected into the system prompt of every pi session. */
  async systemPrompt() {
    return [
      'You have access to live web search results prepended to some user messages.',
      'These results come from a local SearXNG instance and are factual grounding.',
      'Prefer information from search results over training knowledge when relevant.',
      'Cite source URLs from search results when they informed your answer.',
    ].join(' ');
  },

  /**
   * Automatically inject search results as a context footer when the user
   * message matches the trigger regex.  Return null to skip injection.
   */
  async contextFooter({ userMessage }) {
    if (!TRIGGER.test(userMessage)) return null;
    const results = await searxng(userMessage);
    if (!results) return null;
    return \`\\n\\n---\\n## Web Search Results (via SearXNG)\\n\\n\${results}\\n---\`;
  },

  tools: [
    {
      name: 'web_search',
      description:
        'Search the web via local SearXNG for up-to-date information, docs, or error solutions.',
      parameters: {
        type: 'object',
        properties: {
          query: { type: 'string', description: 'The search query' },
        },
        required: ['query'],
      },
      async execute({ query }) {
        const results = await searxng(query);
        return results ?? 'No results found.';
      },
    },
  ],
};
`;
}
