import { spawnSync, spawn } from 'child_process';
import { mkdirSync, writeFileSync, existsSync } from 'fs';
import { resolve } from 'path';
import { config } from './config.js';
import { success, warn, error } from './ui.js';

/**
 * Launch pi in interactive TUI mode.
 * If searchEnabled, the archon-search extension is activated via env.
 */
export function launchPi(searchEnabled = false): void {
  const piArgs = ['--model', `ollama/${config.ollama.model}`];

  const env: NodeJS.ProcessEnv = { ...process.env };
  if (searchEnabled) {
    env.PI_EXTENSIONS = config.pi.extensionName;
    env.ARCHON_SEARXNG_URL = config.searxng.url;
    env.ARCHON_TOP_N = String(config.searxng.topN);
    env.ARCHON_SEARCH_TRIGGER = config.searxng.triggerRegex.source;
  }

  const result = spawn('pi', piArgs, {
    stdio: 'inherit',
    env,
    shell: false,
  });

  result.on('error', (err) => {
    error(`Could not launch pi: ${err.message}`);
    error('Install pi with: npm i -g @oh-my-pi/pi-tui');
  });
}

/**
 * Run pi in print (non-interactive) mode with an instruction and file.
 * Returns the output string.
 */
export function runPiTask(instruction: string, filePath: string, searchContext?: string): void {
  const prompt = searchContext
    ? `${searchContext}\n\nInstruction: ${instruction}`
    : instruction;

  const env: NodeJS.ProcessEnv = { ...process.env };

  const args = [
    '--model', `ollama/${config.ollama.model}`,
    '-p', prompt,
    filePath,
  ];

  const result = spawnSync('pi', args, {
    stdio: 'inherit',
    env,
    encoding: 'utf8',
  });

  if (result.error) {
    error(`pi task failed: ${result.error.message}`);
  }
}

/**
 * Install the archon-search pi extension to ~/.pi/extensions/
 */
export function installExtension(): void {
  const dir = config.pi.extensionDir;
  const outPath = resolve(dir, `${config.pi.extensionName}.mjs`);

  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }

  const extensionSrc = generateExtensionSource();
  writeFileSync(outPath, extensionSrc, 'utf8');
  success(`Pi extension installed → ${outPath}`);
}

function generateExtensionSource(): string {
  return `
// archon-search pi extension
// Auto-generated by archon-cli — do not edit manually
// Re-run 'archon install-extension' to regenerate.

const SEARXNG = process.env.ARCHON_SEARXNG_URL ?? '${config.searxng.url}';
const TOP_N   = parseInt(process.env.ARCHON_TOP_N ?? '${config.searxng.topN}', 10);
const TRIGGER = new RegExp(process.env.ARCHON_SEARCH_TRIGGER ?? '${config.searxng.triggerRegex.source}', 'i');
const CATEGORIES = process.env.ARCHON_SEARCH_CATEGORIES ?? '${config.searxng.categories}';

async function searchWeb(query) {
  try {
    const url = new URL('/search', SEARXNG);
    url.searchParams.set('q', query);
    url.searchParams.set('format', 'json');
    url.searchParams.set('categories', CATEGORIES);

    const res = await fetch(url.toString(), {
      headers: { Accept: 'application/json' },
      signal: AbortSignal.timeout(8000),
    });
    if (!res.ok) return null;

    const data = await res.json();
    const results = (data.results ?? []).slice(0, TOP_N);
    if (results.length === 0) return null;

    return results
      .map((r, i) => \`**[\${i + 1}] \${r.title ?? ''}**\n\${r.url ?? ''}\n\${(r.content ?? r.snippet ?? '').trim()}\`)
      .join('\n\n');
  } catch {
    return null;
  }
}

export default {
  name: 'archon-search',

  async systemPrompt() {
    return [
      'You have access to live web search results prepended to some user messages.',
      'These results come from a local SearXNG instance and are factual grounding.',
      'Prefer information from search results over training knowledge when coding.',
      'Cite source URLs from search results when they informed your answer.',
    ].join(' ');
  },

  async contextFooter({ userMessage }) {
    if (!TRIGGER.test(userMessage)) return null;
    const results = await searchWeb(userMessage);
    if (!results) return null;
    return \`\n\n---\n## Web Search Results (via SearXNG)\n\n\${results}\n---\`;
  },

  tools: [
    {
      name: 'web_search',
      description: 'Search the web via local SearXNG for up-to-date information, docs, or error solutions.',
      parameters: {
        type: 'object',
        properties: {
          query: { type: 'string', description: 'The search query' },
        },
        required: ['query'],
      },
      async execute({ query }) {
        const results = await searchWeb(query);
        return results ?? 'No results found.';
      },
    },
  ],
};
`.trimStart();
}
